#!/bin/bash                                                                                                       

#SBATCH -J dgswem      # Job name                                                                          
#SBATCH -A TG-DMS080016N # seDawson
#SBATCH -o Katrina.o%j       # Name of stdout output file (%j expands to jobId)   
#SBATCH -e Katrina.e%j       # Name of stdout output file (%j expands to jobId)                               
#SBATCH -p development   # Queue name                                                         
#SBATCH -n 256             #Total number of mpi tasks requested
#SBATCH -t 2:00:00      # Run time (hh:mm:ss) - 1.5 hours                                                   
#SBATCH --mail-user=michoski@ices.utexas.edu
#SBATCH --mail-type=ALL 

export MV2_ON_DEMAND_THRESHOLD=256

ibrun ./dgswem

